using EnterpriseFlow.Application.Abstractions;
using Microsoft.Extensions.Options;

namespace EnterpriseFlow.Infrastructure.Storage;

/// <summary>
/// F5.2 — the provider that actually ships by default (ADR-0009/r2-01-vision-y-alcance.md): no
/// external account needed, and the one this repo can verify end-to-end without an emulator.
/// </summary>
public sealed class LocalStorageProvider : IDocumentStorageProvider
{
    private readonly string _basePath;

    public LocalStorageProvider(IOptions<LocalStorageOptions> options)
    {
        _basePath = Path.GetFullPath(options.Value.BasePath);
        Directory.CreateDirectory(_basePath);
    }

    public async Task<string> UploadAsync(Stream content, string fileName, string contentType, CancellationToken cancellationToken)
    {
        var storageKey = $"{Guid.NewGuid():N}{Path.GetExtension(fileName)}";
        var path = Path.Combine(_basePath, storageKey);

        await using var fileStream = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true);
        await content.CopyToAsync(fileStream, cancellationToken);

        return storageKey;
    }

    public Task<Stream> DownloadAsync(string storageKey, CancellationToken cancellationToken)
    {
        var path = ResolvePath(storageKey);
        Stream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, useAsync: true);
        return Task.FromResult(stream);
    }

    public Task DeleteAsync(string storageKey, CancellationToken cancellationToken)
    {
        File.Delete(ResolvePath(storageKey));
        return Task.CompletedTask;
    }

    // storageKey is generated by this class alone (UploadAsync), never derived from user input —
    // Path.Combine can't be used to escape _basePath through it.
    private string ResolvePath(string storageKey) => Path.Combine(_basePath, storageKey);
}
